### ISSUE TITLE
[Bug]: Does not build on OSX while it does on iOS (Glider 2.0.2)

### ISSUE THREAD

**Issue by itsyoshio** [immobiliare/Glider#7]
### Platform Version

macOS 13.4.1

### SDK Version

macOS 11.0

### Xcode Version

Xcode 14.3.1

### Steps To Reproduce

Start a new OSX App, add [GitlabSwift](https://github.com/malcommac/GitLabSwift) as [dependency](https://github.com/malcommac/GitLabSwift#swift-package-manager) (in my case, or Glider directly). Try to build with any MacOS SDK > 10.15.4. (>= 11.0)

### Expected Behavior

Succeed build stage

### Actual Incorrect Behavior

```
Xcode/DerivedData/Sprinter-egqxkwtrztvbhobivewkovutzyni/SourcePackages/checkouts/Glider/Glider/Sources/Transports/File/FileTransport.swift:115:32 
'seekToEnd()' is only available in macOS 10.15.4 or newer

Xcode/DerivedData/Sprinter-egqxkwtrztvbhobivewkovutzyni/SourcePackages/checkouts/Glider/Glider/Sources/Transports/File/FileTransport.swift:116:32 
'write(contentsOf:)' is only available in macOS 10.15.4 or newer

Xcode/DerivedData/Sprinter-egqxkwtrztvbhobivewkovutzyni/SourcePackages/checkouts/Glider/Glider/Sources/Transports/File/FileTransport.swift:118:36 
'write(contentsOf:)' is only available in macOS 10.15.4 or newer
```

**Comment by malcommac** [comment]
merget in 2.0.3 thanks!
